config/routes.rb
Rails.application.routes.draw do
  resources :salaries
  resources :sales
  resources :products
  resources :pelanggans
  resources :montirs, except: [:new]
  resources :forgot_passwords, only: [:create]
  resources :password_resets, only: [:show, :create]
  

  get '/signup', to: 'montirs#new'
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get '/monthly', to: 'sales#monthly_report' 
  get '/forgot_passwords', to: 'forgot_passwords#new'
  get 'expired_token', to: 'password_resets#expired_token'
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'

end

app/views/templates/_footer.html.erb
<footer class="footer">
      <div class="w3-container">
        <h3 style="text-align:center;font-family:garamond;">Angel Ria Purnamasari <%= Time.now.year %></h3>
      </div>
</footer>

app/views/templates/_page_title.html.erb
<h1 style="text-align:center"><%= title.capitalize %></h1>
<hr/>

app/views/templates/_sidebar.html.erb
  <!-- Sidebar -->
<div class="w3-sidebar  w3-bar-block w3-border-right w3-black" 
style="display:none" id="mySidebar">
<button onclick="w3_close()" class="w3-bar-item w3-large">Close &times;</button>
<ul class="nav navbar-nav" style="padding-left:10px;padding-right:15px">
    <li style="padding-top:20px"></li>
    <% if logged_in? %>
        <li>
          <% if current_montir.picture.attached? %>
            <%= image_tag url_for(current_montir.picture), size:'150', class:'img rounded-circle'%>
          <% else %>
               <%= link_to gravatar_for(current_montir), montir_path(current_montir) %>
          <% end %>
          <hr/>
        </li>
        <% if logged_in? && current_montir.admin? %>
          <li><a href="/montirs" class="w3-bar-item w3-button", style="color:white">Dashboard</a></li>
        <% else %>
          <li><a href="/" class="w3-bar-item w3-button", style="color:white">Dashboard</a></li>
        <% end %>
        <li><%= link_to "View your Profile", montir_path(current_montir), class:"w3-bar-item w3-button", style:'color:white'%></li>
        <li><%= link_to "Edit Your Profile", edit_montir_path(current_montir),class:"w3-bar-item w3-button", style:'color:white' %></li>
        <li><a href="pelanggans/new" class="w3-bar-item w3-button", style="color:white">Create New Pelanggan</a></li>
        <li><%= link_to "Log Out", logout_path, method: :delete, class:"w3-bar-item w3-button", style:'color:white'%></li>
     <% else%>
          <li><%= link_to "Log In", login_path, class:"w3-bar-item w3-button", style:"color:white" %></li>
    <% end %>
    <% if !logged_in? %>
      <li><a href="/" class="w3-bar-item w3-button", style="color:white">Dashboard</a></li>
    <% end %>
    <li><a href="pelanggans" class="w3-bar-item w3-button", style="color:white">Daftar Pelanggan</a></li>
    <li><%= link_to "All Sales", sales_path, class:"w3-bar-item w3-button", style:'color:white' %></li>  
    <li><%= link_to "All Products", products_path, class:"w3-bar-item w3-button", style:'color:white' %></li>  
</ul>
</div>