config/routes.rb
Rails.application.routes.draw do
  resources :salaries
  resources :sales
  resources :products
  resources :pelanggans
  resources :montirs, except: [:new]
  resources :forgot_passwords, only: [:create]
  resources :password_resets, only: [:show, :create]
  

  get '/signup', to: 'montirs#new'
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get '/monthly', to: 'sales#monthly_report' 
  get '/forgot_passwords', to: 'forgot_passwords#new'
  get 'expired_token', to: 'password_resets#expired_token'
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'

end

app/models/product.rb
class Product < ApplicationRecord
  before_create :set_code

  belongs_to :montir
  
  has_many :items, dependent: :destroy

  # validation product name
  validates :name, presence: {messages:"Products Name can't be Blank!"},
  length: {maximum: 30, messages:"Product name Max. is 30 Character!"},
  uniqueness: { case_sensitive: true }

  # Validation price name
  validates :price, presence: { messages: "Price can't be Blank!"}

  def generate_code(size = 6)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    (0...size).map{ charset.to_a[rand(charset.size)] }.join
  end

  def set_code
    self.code = generate_code(6)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.montir = current_montir
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def monthly_report
    @product = Product.where(:created_at => (Time.now.midnight - 30.day)..Time.now.midnight)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :name, :price, :montir_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:'form-control', placeholder:'Nama produk', autofocus:true %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price,class:'form-control', placeholder:'Harga Produk', autofocus:true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Edit Product" %>
  </div>
</div>
<%= render 'form', product: @product %>

<%= link_to 'Show', @product, class:'btn btn-success' %> |
<%= link_to 'Back', products_path, class:'btn btn-default' %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Product List" %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.code %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product, class:'btn btn-success', style:'color:white' %></td>
         <% if logged_in? && current_montir.admin? %>   
          <td><%= link_to 'Edit', edit_product_path(product), class:'btn btn-default' %></td>
          <td>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },
              class:'btn btn-danger', style:'color:white' %>
          </td>
         <% else %>
            <td></td>
            <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class:'btn btn-primary', style:'color:white' %>

app/views/products/new.html.erb
<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"New Product Form" %>
  </div>
</div>
<%= render 'form', product: @product %>
<br>
<%= link_to 'Back', products_path, class:'btn btn-default' %>

app/views/products/show.html.erb
<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Detail Product" %>
  </div>
</div>
<div class="container">
  <div class="well col-md-8 col-md-offset-2">
    <div class="row description">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Code:</strong>
        <%= @product.code %>
      </p>

      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @product.price %>
      </p>

      <p>
        <strong>Montir:</strong>
        <%= @product.montir.name %>
      </p>
    </div>
    <%# Showing Montir and create at %>
    <div class="pull-right">
            <p class="center">
                <em>Created By:</em>
            </p>
            <p class="center">
                <% if @product.montir.picture.attached? %>
                    <%= image_tag url_for(@product.montir.picture), size:'150', class:'img rounded-circle'%>
                <% else %>
                    <%= link_to gravatar_for(@product.montir), pelanggans_path%>
                <% end %>
            </p>
            <p class="center">
                <small>
                    <%= @product.montir.name.capitalize %>
                </small>
                <div class="pull-right">
                    <div class="pull-right">Created:<%= time_ago_in_words(@product.created_at)%> ago
                </div>
            </p>
    </div>
  </div>

  <%# Button Edit %>
  <div class="recipe-actions">
    <% if logged_in? && (current_montir == @product.montir || current_montir.admin?) %>
      <%= link_to 'Edit', edit_product_path(@product), class:'btn btn-info' %> |
      <%= link_to 'Back', products_path, class:'btn btn-default' %>
     <% else %>
        <%= link_to 'Back', products_path, class:'btn btn-xs btn-default' %>
    <% end %>
  </div>
</div>