config/routes.rb
Rails.application.routes.draw do
  resources :salaries
  resources :sales
  resources :products
  resources :pelanggans
  resources :montirs, except: [:new]
  resources :forgot_passwords, only: [:create]
  resources :password_resets, only: [:show, :create]
  

  get '/signup', to: 'montirs#new'
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get '/monthly', to: 'sales#monthly_report' 
  get '/forgot_passwords', to: 'forgot_passwords#new'
  get 'expired_token', to: 'password_resets#expired_token'
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'

end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :montir
  belongs_to :pelanggan
  before_save :commision

  
  has_many :items, dependent: :destroy

  accepts_nested_attributes_for :items, allow_destroy: true  
  
  def subtotals  
    self.items.map { |i| i.subtotal }  
  end  
   
  def diskonan
    if diskon.blank?  
      0
    else
      diskon
    end
  end  

  def total_all  
    subtotals.sum - diskonan
  end  
  
  def commision
    total_all * 0.15
  end

  def commision_total
    commision.sum 
  end


end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sale            = Sale.all
    @sale_list       = @sale.group_by { |t| t.montir.name };
    @sale_month      = Sale.where(:created_at => (Time.now - 30.day)..Time.now.midnight);
    @commission      = Sale.sum(:commission)
    @sale_commisions = Sale.group_by_month(:created_at).sum(:commission)
    @date = Date.today.strftime("%m/%Y");
    respond_to do |format|
      format.html
      format.json
      format.pdf do 
        render template:'sales/index.html.erb', layout:'laporan_penggajian.pdf.html', 
        pdf: "Laporan Penggajian-#{@date}",
        disposition: :inline
      end
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
      respond_to do |format|
      format.html
      format.json
      format.pdf do 
        render template:'sales/show.html.erb', layout:'sales.pdf.html', 
        pdf: "#{@sale.pelanggan.nama}(#{@sale.pelanggan.code})-pembayaran",
        disposition: :inline
      end
    end
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.montir = current_montir
    @sale.total = @sale.total_all
    @sale.commission = @sale.commision
    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def monthly_report
    @sale_month = Sale.where(:created_at => (Time.now - 30.day)..Time.now);
    @date = Date.today.strftime("%m/%Y");
    respond_to do |format|
        format.html
        format.json
        format.pdf do
            render template: 'sales/sales_report.html.erb', layout: 'sales_monthly.pdf.html',
            pdf: "Laporan Penjualan-#{@date}",
            disposition: :inline
        end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:name,:montir_id, :pelanggan_id, :no_kendaraan, :diskon, items_attributes: [:id, :product_id, :price, :quantity, :total, :_destroy])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
  <%= form_with(model: sale, local: true) do |form| %>
    <% if sale.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

        <ul>
        <% sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, "Detail Kerusakan" %>
      <%= form.text_field :name , class:'form-control', placeholder:'Detail Kerusakan', autofocus:true%>
    </div>
    <div class="form-group">
      <%= form.label :pelanggan_id, "Nama Pelanggan"%>
      <%= form.collection_select :pelanggan_id, Pelanggan.order(:nama), :id, :nama, class:'form-control'%>
    </div>
    <div class="form-group">
      <%= form.label :no_kendaraan, "Nomor Plat" %>
      <%= form.text_field :no_kendaraan , class:'form-control', placeholder:'Nomor Plat Kendaraan', autofocus:true%>
    </div>
    <%# Nested Form Items %>
    <div class="form-group">
      <%= form.fields_for :items do |builder| %>
        <%= render 'item_fields', form: builder%>
      <% end %>
    </div>
    <%= link_to_add_fields "Add Item", form, :items %>
    <%# Form Diskon %>
    <div class="form-group">
      <%= form.label :diskon, "Potongan Harga" %>
      <%= form.text_field :diskon , class:'form-control', placeholder:'Diskon', autofocus:true%>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

  <%# Script for Items %>
 <script type="text/javascript">   
  jQuery(function() {   
   $('form').on('click', '.remove_fields', function(event) {   
   $(this).prev('input[type=hidden]').val('1');   
   $(this).closest('fieldset').hide();   
   return event.preventDefault();   
   });   
   return $('form').on('click', '.add_fields', function(event) {   
   var regexp, time;   
   time = new Date().getTime();   
   regexp = new RegExp($(this).data('id'), 'g');   
   $(this).before($(this).data('fields').replace(regexp, time));   
   return event.preventDefault();   
   });   
  });   
  </script>   

app/views/sales/_item_fields.html.erb
 <fieldset>  
  <%= form.label :product, "Product" %>  
  <%= form.collection_select :product_id, Product.all, :id, :name, class:'form-control' %>  
  <%= form.label :quantity, "Quantity" %>  
  <%= form.text_field :quantity, class: 'padli form-control', placeholder:'Jumlah barang' %>  
  <%= form.hidden_field :_destroy %>  
  <%= link_to "remove", '#', class: "remove_fields" %>  
 </fieldset>  

app/views/sales/_report.html.erb
<tbody>    
    <% obj.each do |month, sales| %>  
      <strong><%= month.strftime('%B %Y') %></strong>
      <hr>
      <tr>
        <% for sale in sales %>
        <div>
          <div class="container">
            <div class="row">
                <p><strong>NIP:</strong><%= sale.pelanggan.code%></p>
            </div>
            <%= sale.pelanggan.nama%>
            <%= sale.name %></td>
            <%= sale.no_kendaraan %>
            <%= sale.total_all %>
            <%= sale.montir.name %>
            <%= sale.commision %>
            <%= link_to 'Show', sale, class:'btn btn-success', style:'color:white'%>
            <%= link_to 'Edit', edit_sale_path(sale),class:'btn btn-default' %>
            <%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' },
              class:'btn btn-danger', style:'color:white'%>
          </div>
        </div>
          <%# <%= @sale_commisions%>
        <% end %>
      </tr>
      <tr>
      </tr>
    <% end %>
</tbody>

app/views/sales/_sale.html.erb
<tbody>    
    <% obj.each do |sale| %>  
            <td><%= sale.pelanggan.code%></td>
            <td><%= sale.pelanggan.nama%></td>
            <td><%= sale.name %></td>
            <td><%= sale.no_kendaraan %></td>
            <td><%= sale.total_all %></td>
            <td><%= sale.montir.name %></td>
            <td><%= sale.commision %></td>
            <td><%= link_to 'Show', sale, class:'btn btn-success', style:'color:white'%></td>
            <% if logged_in? && (current_montir == sale.montir || current_montir.admin?) %>
              <td><%= link_to 'Edit', edit_sale_path(sale),class:'btn btn-default' %></td>
              <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' },
                class:'btn btn-danger', style:'color:white'%></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
      </tr>
    <% end %>
</tbody>

app/views/sales/_slip.html.erb
<tbody>    
    <% obj.each do |month, sales| %>  
      <strong><%= month.strftime('%B %Y') %></strong>
      <hr>
      <tr>
        <% for sale in sales %>
        <div>
          <div class="container">
            <div class="row">
                <p><strong>NIP:</strong><%= sale.pelanggan.code%></p>
            </div>
            <%= sale.pelanggan.nama%>
            <%= sale.name %></td>
            <%= sale.no_kendaraan %>
            <%= sale.total_all %>
            <%= sale.montir.name %>
            <%= sale.commision %>
        </div>
          <%# <%= @sale_commisions%>
        <% end %>
      </tr>
      <tr>
      </tr>
    <% end %>
</tbody>

app/views/sales/edit.html.erb
<div class="w3-black w3-container">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Edit Data Sales" %>
  </div>
</div>
<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale, class:'btn btn-info' %> |
<%= link_to 'Back', sales_path, class:'btn btn-default' %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>
<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Service List" %>
  </div>
</div>

<table class="table table-striped" style="overflow-x:auto;">
  <thead>
    <tr>
      <th>No.Sales</th>
      <th>Nama Pelanggan</th>
      <th>Detail Kerusakan</th>
      <th>Nomor Plat</th>
      <th>Total</th>
      <th>Montir</th>
      <th>Komisi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render 'sale', obj: @sale%>
  </tbody>
</table>

<br>
<div class="recipe-actions">
  <%= link_to 'New Sale', new_sale_path, class:'btn btn-primary', style:'color:white'  %>
  <% if logged_in? && (current_montir.admin?) %>
    <%= link_to 'Laporan Penggajian', sales_path(@sale, :format => :pdf), class:'btn btn-success' %>
    <%= link_to 'Laporan Sales', monthly_path(@sale_month, :format => :pdf), class:'btn btn-warning' %>
  <% end %>
</div>

app/views/sales/new.html.erb
<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"New Sale Data" %>
  </div>
</div>
<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path, class:'btn btn-default' %>

app/views/sales/sales_report.html.erb
<tbody>    
    <% @sale_month.each do |sale| %>  
      <strong><%= @date %></strong>
      <hr>
      <tr>
        <div>
          <div class="container">
            <div class="row">
                <p><strong>NIP:</strong><%= sale.pelanggan.code%></p>
            </div>
            <%= sale.pelanggan.nama%>
            <%= sale.name %></td>
            <%= sale.no_kendaraan %>
            <%= sale.total_all %>
            <%= sale.montir.name %>
            <%= sale.commision %>
          </div>
        </div>
      </tr>
      <tr>
      </tr>
    <% end %>
</tbody>

app/views/sales/show.html.erb
<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Detail Penjualan / Sale" %>
  </div>
</div>

<%# Content %>
<div class="container">
  <div class="well col-md-8 col-md-offset-2">
    <%# Detail Data %>
    <div class="pull-left">  
    <ul>
      <hr/>
      <li>
          <strong>NIP:</strong>
          <%= @sale.pelanggan.code %>
      </li>
      <br>
      <li>
          <strong>Nama Customer:</strong>
          <%= @sale.pelanggan.nama %>
      </li>
      <br>
      <li>
          <strong>Plat Kendaraan:</strong>
          <%= @sale.no_kendaraan %>
      </li>
    </ul>
    </div>
    <%# Detail Nomor Perbaikan %>
    <div class="pull-right">
      <ul>
        <li>  
            <strong>Nomor ID Service:</strong>
            <%= @sale.id %>
        </li>
      </ul>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Product</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Subtotal</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @sale.items.each do |item| %>
        <tr>
          <td><%= item.product.name %></td>
          <td><%= item.product.price %></td>
          <td><%= item.quantity %></td>
          <td><%= item.subtotal %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <hr/>
    <%# Memunculkan Potongan Harga / Diskon %>
    <p class="pull-right">
      <p><strong>Potongan Harga:</strong></p>
      <%= @sale.diskon %>
     <%# Showing Total %>
      <p><strong>Total yang harus di bayar:</strong></p>
      <%= @sale.total_all %>
    </p>
   
    
    
    <%# Showing Montir and create at %>
    <div class="pull-right">
            <p class="center">
                <em>Created By:</em>
            </p>
            <p class="center">
                <small>
                    <%= @sale.montir.name.capitalize %>
                </small>
                <div class="pull-right">
                    <div class="pull-right">Created:<%= @sale.created_at %>
                </div>
            </p>
    </div>
  </div>

  <%# Button Edit %>
  <div class="recipe-actions">
    <% if logged_in? && (current_montir == @sale.montir || current_montir.admin?) %>
      <%= link_to 'Edit', edit_sale_path(@sale), class:'btn btn-xs btn-info' %> |
      <%= link_to 'Back', sales_path, class:'btn btn-xs btn-default' %> | 
      <%= link_to 'Print Bill', sale_path(@sale, :format => :pdf), class:'btn btn-xs btn-success' %>
    <% else %>
        <%= link_to 'Back', sales_path, class:'btn btn-xs btn-default' %>
    <% end %>
  </div>
</div>