config/routes.rb
Rails.application.routes.draw do
  resources :salaries
  resources :sales
  resources :products
  resources :pelanggans
  resources :montirs, except: [:new]
  resources :forgot_passwords, only: [:create]
  resources :password_resets, only: [:show, :create]
  

  get '/signup', to: 'montirs#new'
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'

  get '/monthly', to: 'sales#monthly_report' 
  get '/forgot_passwords', to: 'forgot_passwords#new'
  get 'expired_token', to: 'password_resets#expired_token'
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'

end

app/models/pelanggan.rb
class Pelanggan < ApplicationRecord
    # Association with Montir Table
    belongs_to :montir

    # Sebelum Save akan di generate code Unique untuk id Pelanggan
    before_create :set_code

    # Association with Sales Table
    has_many :sales, dependent: :destroy
    # For Validation these column can't be Blank
    validates :nama, presence: {messages: "Pelanggan name can't be blank!"},
    length: {maximum:30, messages:"Name Max. Length is 30 character!"}
    validates :alamat, presence: true
    validates :no_telp, presence: true
    validates :montir_id, presence:true

    def generate_code(size = 6)
        charset = %w{1 2 3 4 5 6 7 8 9 0 }
        (0...size).map{ charset.to_a[rand(charset.size)] }.join
      end
    
      def set_code
        self.code = generate_code(6)
      end
    
end

app/controllers/pelanggans_controller.rb
class PelanggansController < ApplicationController
  before_action :set_pelanggan, only: [:show, :edit, :update, :destroy]

  # GET /pelanggans
  # GET /pelanggans.json
  def index
    @pelanggans = Pelanggan.all
  end

  # GET /pelanggans/1
  # GET /pelanggans/1.json
  def show
  end

  # GET /pelanggans/new
  def new
    @pelanggan = Pelanggan.new
  end

  # GET /pelanggans/1/edit
  def edit
  end

  # POST /pelanggans
  # POST /pelanggans.json
  def create
    @pelanggan = Pelanggan.new(pelanggan_params)
    @pelanggan.montir = current_montir
    respond_to do |format|
      if @pelanggan.save
        format.html { redirect_to @pelanggan, notice: 'Pelanggan was successfully created.' }
        format.json { render :show, status: :created, location: @pelanggan }
      else
        format.html { render :new }
        format.json { render json: @pelanggan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pelanggans/1
  # PATCH/PUT /pelanggans/1.json
  def update
    respond_to do |format|
      if @pelanggan.update(pelanggan_params)
        format.html { redirect_to @pelanggan, notice: 'Pelanggan was successfully updated.' }
        format.json { render :show, status: :ok, location: @pelanggan }
      else
        format.html { render :edit }
        format.json { render json: @pelanggan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pelanggans/1
  # DELETE /pelanggans/1.json
  def destroy
    if !current_montir.admin?
      @pelanggan.destroy
      respond_to do |format|
        format.html { redirect_to pelanggans_url, notice: 'Pelanggan was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def monthly_report
    @pelanggan = Pelanggan.where(:created_at => (Time.now - 30.day)..Time.now.midnight)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelanggan
      @pelanggan = Pelanggan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pelanggan_params
      params.require(:pelanggan).permit(:code, :nama, :alamat, :no_telp, :no_kendaraan, :d_kerusakan, :montir_id, :status)
    end
end

app/helpers/pelanggans_helper.rb
module PelanggansHelper
end

app/views/pelanggans/_form.html.erb
<div style="container">
<%= form_with(model: pelanggan, local: true) do |form| %>
  <% if pelanggan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pelanggan.errors.count, "error") %> prohibited this pelanggan from being saved:</h2>

      <ul>
      <% pelanggan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :nama %>
    <%= form.text_field :nama, class:'form-control', placeholder:'Nama Pelanggan' %>
  </div>

  <div class="form-group">
    <%= form.label :alamat %>
    <%= form.text_area :alamat, class:'form-control', placeholder:'Masukkan Alamat Pelanggan' %>
  </div>

  <div class="form-group">
    <%= form.label :no_telp %>
    <%= form.text_field :no_telp,class:'form-control', placeholder:'Masukkan Nomor Telephone Pelanggan'%>
  </div>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
</div>

app/views/pelanggans/_pelanggan.html.erb
  <% obj.each do |pelanggan| %>
      <tr>
        <td><%= pelanggan.code %></td>
        <td><%= pelanggan.nama %></td>
        <td><%= pelanggan.alamat %></td>
        <td><%= pelanggan.no_telp %></td>
        <td><%= link_to 'Show', pelanggan, class:'btn btn-success', style:'color:white' %></td>
        <% if logged_in? && (current_montir == pelanggan.montir || current_montir.admin?) %>
          <td><%= link_to 'Edit', edit_pelanggan_path(pelanggan), class:'btn btn-default' %></td>
          <td><%= link_to 'Destroy', pelanggan, method: :delete, data: { confirm: 'Are you sure to delete this record?' },
          class:'btn btn-danger', style:'white' %></td>
         <% else %>
            <td></td>
            <td></td>
        <% end %>
      </tr>
    <% end %>
       

app/views/pelanggans/edit.html.erb
<div class="w3-black w3-container">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Edit Data Pelanggan" %>
  </div>
</div>

<%= render 'form', pelanggan: @pelanggan %>

  <%= link_to 'Show', @pelanggan, class:'btn btn-success' %> |
  <%= link_to 'Back', pelanggans_path, class:'btn btn-default' %>

app/views/pelanggans/index.html.erb
<p id="notice"><%= notice %></p>

<%# Header with Sidebar Button %>
<div class="w3-container w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Index Data Pelanggan" %>
  </div>
</div>

<%# Content %>
<table class="table table-striped" style="overflow-x:auto;" >
  <thead>
    <tr>
      <th>NIP</th>
      <th>Nama</th>
      <th>Alamat</th>
      <th>Nomor telp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# Render Pelanggan Lists %>
    <%= render 'pelanggan', obj: @pelanggans %>
      
  </tbody>
</table>

<br>

<%= link_to 'New Pelanggan', new_pelanggan_path, class:'btn btn-primary', style:'color:white' %>

app/views/pelanggans/new.html.erb
<div class="w3-black w3-container">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Create New Pelanggan" %>
  </div>
</div>

<%= render 'form', pelanggan: @pelanggan %>
<%= link_to 'Back', pelanggans_path, class:'btn btn-default' %>

app/views/pelanggans/show.html.erb
<div class="w3-black">
  <button class="w3-button w3-black w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <%= render 'templates/page_title', title:"Pelanggan Detail" %>
  </div>
</div>
  <div class="container">
    <div class="well col-md-8 col-md-offset-2">
      <p id="notice"><%= notice %></p>
      <div class="pull-left">
          <table class="center description" >
            <tbody>
              <%# Column Nomor Identitas Pelanggan sesuai KTP %>
              <tr>
                <td><strong>Nomor Identitas Pelanggan</strong></td>
                <td><%= @pelanggan.code %></td>
              </tr>

              <%# Column Nama Pelanggan %>
              <tr>
                <td><strong>Nama</strong></td>
                <td><%= @pelanggan.nama %></td>
              </tr>

              <%# Column Alamat %>
              <tr>
                <td><strong>Alamat</strong></td>
                <td><%= @pelanggan.alamat %></td>
              </tr>

              <%# Column No_telp %>
              <tr>
                <td><strong>No telp</strong></td>
                <td><%= @pelanggan.no_telp %></td>
              </tr>
            </tbody>
          </table>
      </div>
          <div class="pull-right">
            <p class="center">
                <em>Created By:</em>
            </p>
            <p class="center">
                <% if @pelanggan.montir.picture.attached? %>
                    <%= image_tag url_for(@pelanggan.montir.picture), size:'150', class:'img rounded-circle'%>
                <% else %>
                    <%= link_to gravatar_for(@pelanggan.montir), pelanggans_path%>
                <% end %>
            </p>
            <p class="center">
                <small>
                    <%= @pelanggan.montir.name.capitalize %>
                </small>
                <div class="pull-right">
                    <div class="pull-right">Created:<%= time_ago_in_words(@pelanggan.created_at)%> ago
                </div>
            </p>
          </div>
          <%# Button Edit %>
        <div class="recipe-actions">
          <% if logged_in? && (current_montir == @pelanggan.montir || current_montir.admin?) %>
            <%=   link_to 'Edit', edit_pelanggan_path(@pelanggan), class:'btn btn-info' %>
          <% end %>
            <%= link_to 'Back', pelanggans_path, class:'btn btn-default' %>
        </div>
    </div>
    
  </div>